### ISSUE TITLE
@rchampieux and @aversluis will take the lead on drafting plan for July deliverables.  

### ISSUE THREAD

**Issue by rchampieux** [sparcopen/Open-Action-Kit#10]

**Comment by rchampieux** [comment]
### July
#### Kick off communication or virtual forum, which introduces OA Week 2017 and the resources we will be providing to librarians to facilitate successful actions.  The communication or forum will address: 

* high level info on this year's theme ("open in order to...")
* the kinds of actions/engagement being promoted, specifically the "Open in Order To..." campaigns and doathons
* the specific help we'll be providing between now and October
* call for feedback regarding help/resources our audience would value.

**Comment by aversluis** [comment]
[July Kick Off Communications - OA Week 2017 google doc](https://docs.google.com/document/d/1eoaXkECCiaaiDIK_zFn4m8t_9a1mrIvGZ8I7Wzhv7qY/edit?usp=sharing)
