### ISSUE TITLE
@camillet and @emolls will draft plan for August deliverables.

### ISSUE THREAD

**Issue by rchampieux** [sparcopen/Open-Action-Kit#11]
#### Set of light-weight resources that help our audience identify the particular action/s they want to facilitate and move forward with planning, with an emphasis on partnering with local/institutional communities, aligning plans and messaging with institutional goals and interests, and taking your advocacy to the next level.  Potential products include:

* Curated lists of existing resources.  Leveraging @camillet idea of making existing resources easier to use and navigate.
* Inventorying your current environment, resources
* Talking points
* Live or blogged "show and tell"  of specific types of actions, to inspire different models of local activities.
* Forum or blogged interviews on the subject of community engagement and institutional goals alignment.

**Comment by camillet** [comment]
Talking Points [https://github.com/sparcopen/ecl-oaweek/issues/9](url)

**Comment by camillet** [comment]
Google Doc for August Plan: https://docs.google.com/document/d/14SQSuKmv-86i0T3l1F41GfaD8AylQ4WKxkJb0rIllcI/edit?usp=sharing
