### ISSUE TITLE
Robin and Chealsye will draft plan for October.

### ISSUE THREAD

**Issue by rchampieux** [sparcopen/Open-Action-Kit#13]

**Comment by chealsye** [comment]
@rchampieux How do we want to disseminate this information and timeline for sharing? By each week? One packet for the month?

It may be best to tackle these separately as individual topics as we draft them out. How about a single google doc with different sections?

**Comment by rchampieux** [comment]
Hi @chealsye, yes a sectioned google doc works for me.  In regards to the dissemination timing, I don't feel strongly either way.  I think each week would be a lot to manage, but we could possible break it into two packs:  1.) tips, tricks, connecting to the larger community / 2.) preparing for bragging. 

Here's a Google Doc for getting started:  https://docs.google.com/document/d/1oxGn2lOcq0q3bh-iKnkvhQT7WXAJPRTLhg4qxO4rB2I/edit#heading=h.wipifl6vmnzz

**Comment by chealsye** [comment]
Thanks, @rchampieux! I've added some sections to it. Let's go ahead and plan then for two packs.
