### ISSUE TITLE
@emolls and @parnopaeus will draft plan for November deliverables.

### ISSUE THREAD

**Issue by rchampieux** [sparcopen/Open-Action-Kit#14]
#### Resources that address strategies for building on and telling the story of your success via/to various forums and audiences (e.g. institutional peers, administrators, your CV).

**Comment by parnopaeus** [comment]
I just got some interesting Twitter mentions (in the #fuckyeahoawomen thread) about the benefits of self-promotion from Charlotte Rock & Jill Cirasella. Asked them if they might be interested in talking about our topic. Webcast/workshop possibility?
