### ISSUE TITLE
Team Member Info for Website

### ISSUE THREAD

**Issue by rchampieux** [sparcopen/Open-Action-Kit#18]
### Open Action Kit team members please comment with the following info, so I can add this info to our website's team member page.  All fields are optional of course.

* Name
* Position, Organization
* Link to your preferred head shot photo
* Contact info
* Twitter handle

**Comment by rchampieux** [comment]
Robin Champieux
Scholarly Communication Librarian, OHSU
http://openinsightpdx.com/wp-content/uploads/2016/07/Robin-150x150.png
champieu@ohsu.edu
@rchampieux

**Comment by aversluis** [comment]
Ali Versluis
Research and Scholarship Librarian at the University of Guelph 
https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/3/005/077/2aa/20f65e6.jpg 
versluis@uoguelph.ca
@aliversluis

**Comment by camillet** [comment]
Camille Thomas
Scholarly Communication Librarian, Texas Tech University
https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAaBAAAAJGVjM2IyOGVlLTA5ODgtNGMxYS04YzY5LTI2MGU1MGZmOWUxMQ.jpg 
camille.thomas@ttu.edu
@afrofuturistlib

**Comment by parnopaeus** [comment]
Lauren B. Collister
Scholarly Communications Librarian, University Library System, University of Pittsburgh
https://www.dropbox.com/s/ad9wz4tbzamizkh/opencon-square-sm.jpg?dl=0
lbcollister@pitt.edu
@parnopaeus

**Comment by coateshl** [comment]
Heather L. Coates
Digital Scholarship & Data Management Librarian, IUPUI University Library Center for Digital Scholarship    https://iu.box.com/s/t3tl3fpqe3t0h4p5mtfxf6szpde3cxe7
hcoates@iupui.edu
@IandPangurBan

**Comment by emolls** [comment]
Emma Molls
Publishing Services Librarian, University of Minnesota
http://www.acrl.ala.org/acrlinsider/wp-content/uploads/Emma-Molls.jpg
@emma_molls

**Comment by chealsye** [comment]
Sorry for the delay! I was camping over the weekend without internet and wasn't able to get to a computer in time to get a link to an image.

Chealsye Bowley
Community Manager, Ubiquity Press
http://www.ubiquitypress.com/media/up/39934e6a-cfa9-4c4c-ba68-6a6ce7f80f25.png
@chealsye
chealsye.bowley@ubiquitypress.com
