### ISSUE TITLE
Github Q&A! Ask all your silly (and not silly) questions about Github :) 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/Open-Action-Kit#3]

**Comment by parnopaeus** [comment]
What is a pull request, exactly, and how might it be useful for this project?

**Comment by camillet** [comment]
How does github connect with slack? Someone mentioned some kind of chat feature or something? Was that the comment system or is that different?

**Comment by chealsye** [comment]
How can I turn off github notifications to Slack? Every new issue is sending it to the ECL slack AND my email. Don't need both! All the Slack notifications will take away (for me) from its usefulness to chat through Slack.

**Comment by JosephMcArthur** [comment]
> What is a pull request, exactly, and how might it be useful for this project?

It's kind of the equivalent of a suggested edit on Gdocs. Here it's a way of saying "I have an edit for your thing, and here it is". Here, edits are controlled more carefully than on other collaboration systems as in code edits need to be tracked & discussed a lot more heavily.

If we want to store documents on here, and have them worked on here, for many pull request is how they'll contribute. In my opinion this works well for things which don't change much, like web pages & resources once you've fleshed out an initial structure. It's not great for note taking, fast collaboration, or real time co-authoring though. However, Hack.md is good for that, and the notes there translate really well to files here. 

The language / workflows used here, like "pull request" can be tricky to understand. Some further reading that might be helpful is http://michaeljaylissner.com/posts/2014/10/06/editing-on-github-a-non-technical-explainer/

> How does github connect with slack? Someone mentioned some kind of chat feature or something? Was that the comment system or is that different?

@rchampieux set up an integration. We can chat on Slack, the system here is more of a commenting system. 

> How can I turn off github notifications to Slack?

I think @rchampieux can choose what gets posted. I'd also suggest toning it back a bit, perhaps to just new issues or something like that.

**Comment by rchampieux** [comment]
@chealsye and @JosephMcArthur I'll disabled the Slack integration - agreed, not very helpful getting pinged there about Github updates.

**Comment by rchampieux** [comment]
@JosephMcArthur is it just me, or does the Tab key not work in issues?

**Comment by rchampieux** [comment]
#### @parnopaeus here's a use case example of a pull request and why they can be very useful when you have lots of collaborators:

For CSV.conf, speakers could access the Github repository and add their own photos and talk abstracts.  I did this via the following steps, which is pretty standard.

1.  I went to the CSV.conf website repository and made a personal copy of the site.  This is called "forking".  You make a personal copy (and are required to do so), so you don't make unwanted edits to the original source site/code and/or can experiment on the original.

2.  Via my local copy, I added my photo and updated my talk abstract, then saved my changes.  This is called a "Commit".

3.  Then,  I asked the CSV.conf website repository managers to integrate my updates.  This is the "Pull Request", as I'm asking them to pull in my changes.  

#### Where things went wrong and why the Pull request functionality helped:

When I made my changes, I mistakenly **deleted all of the diacritics in the original file!**  I was working on my copy, so this mistake didn't break the public website 🎆 😃 👍   

While I didn't realize my error until after my first Pull Request, I was able to close (or essentially cancel) the request, and create a new one without the diacritic deletions.  

Even if I hadn't noticed my mistake, the CSV.conf site administrators would have seen it when they reviewed my Pull Request, as it provides a line-by-line report on additions and deletions.

**Comment by JosephMcArthur** [comment]
@sparcopen/ecl-team going to keep this open for a bit longer. Keep your Q's coming in if you're not feeling comfortable.
