### ISSUE TITLE
Articulate pitch/summary for ECL call

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/Open-Action-Kit#4]
Things to say:
- [ ] Ask for input ideas for actions/resources
- [ ] What do we already have, not having to reinvent the wheel.

(https://librariandesignshare.org/

**Comment by parnopaeus** [comment]
Outline for the pitch:
-Overall idea for what we're trying to do ("Equip early career librarians with skills, experiences, and "products" that will help them pursue leadership positions and advocate for Open in those positions.")
-Some of the actions for what will lead to this (1. Professional Development activities around 'translating' actions into CV / Resume items, 2. Interviews with admins who are at high levels on what things they're looking for, 3. Actual projects to work on to be able to add those items to your CV / profile) Idea request: Have you done work like this yourself? What have you found useful / helpful? 
-One project we're working on is helping to facilitate OA Week ideas / reporting out. Idea request: what resources for OA week have you found inspirational or helpful? What do you wish existed?

**Comment by rchampieux** [comment]
@parnopaeus here is a first stab at some language describing the above and what we generally discussed today.  Have at it! I will check in again on Monday morning. 🔨 😸 🌈 🐤 

##  Pitch Outline: 

* We are a community of open scholarship advocates, educators, and librarians.  Our experience and vision will benefit the future of libraries and enable a sustainable system of open access, data, and education.

* Nevertheless, the pathways to leadership within and outside of academia can be difficult to navigate.  This is especially true when one's leadership experience takes place outside of a traditional managerial role.  

* Developing strategies to effectively advocate for and communicate our leadership experience, innovations, and impact is essential to personal career advancement.

* As such, SPARC is launching a community effort and pilot project to provide early career librarians with skills, experiences, and products that will help them pursue leadership positions and advocate for open in those positions.

* The pilot project will include a series of suggested actions, open and re-usable resources, and learning opportunities leading up to International Open Access Week 2017.  With the pilot we aim to provide:
   * A progressive strategy and resources for hosting an OA Week related event or advocacy campaign.
       * Beginning with tips on identifying an approach that will resonate with your campus community, and finding partners. 
   * Practical advice for describing and providing evidence of your professional and leadership experience and impact.
       * Including within the context of your CV.
   * Advice and insight from current library leaders who want to help you succeed!

### Call to Action! 

We want your experience and ideas to drive this project, and we definitely don't want to reinvent the wheel.  Please tell us about your successes, resources, and needs (probably need to add some more specific suggestions for the kinds of info we're seeking).

**Comment by JosephMcArthur** [comment]
Have you thought at all about where to send people during the call to action? Sending them to Github makes sense in many ways, but your call.  

You also could ask people to watch this repo too, that'll mean they get updates when stuff happens here. This is what Mozilla study groups do. Some language from them:

> Watch this repo: up in the top right, there's a button that says 'Watch'; click it, and set yourself to 'Watching'. This will send you email notifications of new discussions; if you don't want email, but would like an alert just on GitHub, change the setting in Settings -> Notification Center (Settings is the little cog in the top right). (cite: https://github.com/minisciencegirl/studyGroup)

**Comment by rchampieux** [comment]
Yes @JosephMcArthur I was thinking it would be good to send contributors to Github as well and I like the MSC watch suggestion as well!

**Comment by nshockey** [comment]
Since GitHub might be initially intimidating for some of the people who might want to contribute, what would the group think about setting up a Google Form or other lower-tech way to capture interest? I think we can onboard people to use GitHub quickly, but I'd hate to lose people because they aren't familiar with using GitHub.

**Comment by jangondol** [comment]
@nshockey Would it help to create a [Gitter](https://gitter.im/) chat room for first-time contributors? All that's required for someone to participate is having a GitHub or Twitter account (or the willingness to create one) and the ability to write a message. Here's what a Gitter chat looks like: https://gitter.im/openworm/PyOpenWorm

**Comment by nshockey** [comment]
Thanks, Jan. I agree that people should be able to pickup how to use GitHub quickly. My concern is that when you're trying to recruit volunteers for a project, you want to lower the barriers to joining as much as possible, and I worry that we'll lose folks if we only point to GitHub. @chealsye @JosephMcArthur @parnopaeus @rchampieux any thoughts?

**Comment by JosephMcArthur** [comment]
I think that makes sense. I'm happy to boot up a page on the OpenCon site before the call that could be used. Can handle an auto-response there too automatically, and it will just look a touch more professional I think. We could also probably embed a g-form on the projects website: https://sparcopen.github.io/ECL-OAWeek/. 

I think this is best at least until we've added more to this repo to make it non-github friendly.

**Comment by nshockey** [comment]
Sounds good to me! Thanks, Joe. Do others have thoughts?

**Comment by jangondol** [comment]
@nshockey Understood. Having Gitter as the first point of contact would lower the barriers considerably (a ton of people have at least a Twitter account, which is enough to join the Gitter chat) but ideally there should be a way to also contribute with no account at all.

**Comment by parnopaeus** [comment]
I think these are all great thoughts, from starting off with a form to be notified of happenings to suggesting that people watch the github page for updates if they'd like. If someone is very keen on contributing but doesn't use github, we can onboard them in some way. 

Robin, your outline is very good! As I mentioned, I don't want to be the one talking about this since I'm often the call moderator, so whoever else wants to do it would be A-OK with me!

**Comment by chealsye** [comment]
Either a page on the OpenCon site or a Google form is best, I think. I don't support the use of Gitter. Although it is a good plan for longterm onboarding, I think we need to provide the lowest possible barrier to get people to show their interest and that will be best achieved by giving them something they are familiar with.

**Comment by chealsye** [comment]
Also, @rchampieux and @parnopaeus I think the pitch looks great! Sorry I was unable to look at it until an hour before the call! Will be on today, but will like @rchampieux or @camillet take the lead on that as I talk too frequently on these calls.

**Comment by rchampieux** [comment]
Hi @parnopaeus @Joseph/McArthur @nshockey @chealsye @jangondol.  Great feedback, thank you!  To sum up, it sounds like:   

* everyone is happy with the pitch.  
* We need / will spin up a low-barrier contribution portal - i.e. a branded Google form, but also support contributions through Github. 
* We'll also organize (for those who want it) some Github training (I'll likely team up with Joe and Danielle Robinson to organize this).

I will be a little late for the call (on the train now), but can pitch the project at the end of the call (that is if @camillet doesn't have a chance to review this).

**Comment by coateshl** [comment]
Hi all, just getting back from a trip, so I'm still catching up. @rchampieux the pitch looks good to me. Google Drive seems like a reasonable option for a low barrier entry point to the project. I'll be on the call today, but have to leave early for another meeting.

**Comment by JosephMcArthur** [comment]
FYI, I have a shell of a page here: http://www.opencon2017.org/ecl-oaweek. If you have any edits to the page title, intro or autoresponser let me know!

**Comment by JosephMcArthur** [comment]
Have added an intro from the above, a really short auto responder. @rchampieux will get notified about everyone who signs up!

**Comment by JosephMcArthur** [comment]
Need @rchampieux to do some follow up with the people who signed up
