### ISSUE TITLE
May 19th agenda

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/Open-Action-Kit#6]
Starting a thread for folks to submit anything for our next meeting (not sure if this is helpful, if not just close). 

cc: @sparcopen/ecl-team

**Comment by nshockey** [comment]
Update from OA Week Advisory Committee call regarding how planning for this year's week is evolving / how our ECL group can fit into the larger effort

**Comment by rchampieux** [comment]
* Review roadmap (which Robin will send tomorrow 🤓)
* Review ideas for weekly activities, and prioritize our +1s
* Outline our ideal calendar, including start date and frequency
* Discuss partners and partner resources

**Comment by JosephMcArthur** [comment]
Can I suggest:
* a quick review of open issues & see what's needed to close them

I normally have that as a standing agenda item :)

**Comment by JosephMcArthur** [comment]
closing, we're having the meeting now :D 

agenda is here: https://hackmd.io/CYTgjAzAHCDswFoIAYJgQFgGYgIYJBAgGMFQRkA2AVijVgCZKg==?both
