### ISSUE TITLE
Consider using lowercase for repository name and URLs (file names)

### ISSUE THREAD

**Issue by jangondol** [sparcopen/Open-Action-Kit#7]
Current state: The repository name is currently mixed case (ECL-OAWeek) and so are the URLs, e.g. https://sparcopen.github.io/ECL-OAWeek/

Desired state: Use all lowercase for all URLs and file names.

Reasoning: avoiding mixed case is not only more elegant (this is subjective, of course, YMMV) but it's also more practical. Why?

- Lowercase version of the first URL will work: https://github.com/sparcopen/ecl-oaweek -- the page opens fine
- Lowercase version of the second URL will fail: https://sparcopen.github.io/ecl-oaweek/ -- you'll see an error message

I would hate to dictate to someone the URL to https://sparcopen.github.io/ECL-OAWeek/ over the phone, along with proper cases for all the letters (ecl dash o a week with capital ecl, capital o, capital a, capital w and lowercase e e k). While you don't have to pronounce the URL often, sometimes you need to do that and doing so with mixed case makes it much harder.

And it's not just URLs, it's also file systems (this affects people who clone the repository to work on it). Some computers (or file systems) are case-sensitive and some aren't. So if you have the "OAWeek" repository on a Windows machine and look for "oaweek", you'll find it just fine. If you do the same on Linux, you will see nothing unless you search for the exact mixed-case string ("OAWeek"). And to make this even more fun, Mac can have it both ways, depending on how a particular disk was formatted.

So unless there is a very good reason to use mixed case, can we just be practical, make it easy for ourselves and use all-lowercase instead?

**Comment by JosephMcArthur** [comment]
I have 0 objections here, just one of timing. This is about to get its first bit of publicity, and I don't want to mess around with URL's right before then!

Assigning to this sprint & to myself to change unless I hear objections.

**Comment by JosephMcArthur** [comment]
I've now changed this! Thanks @jangondol
